# Forest Night — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/forest-night/theme.toml.
# Sourced from ~/.dots/fish/.config/fish/conf.d/00-rice.fish.

set -gx EZA_CONFIG_DIR ~/.rice/eza

# eza applies LS_COLORS then EZA_COLORS *after* theme.yml, so these reclaim
# the ten classic file-kind codes from whatever LS_COLORS this system
# already exports (dircolors) — matches ~/.rice/eza/theme.yml's filekinds.
set -gx EZA_COLORS "di=1;38;2;47;107;68:ln=3;38;2;79;216;176:ex=1;38;2;75;171;109:pi=38;2;224;184;79:so=38;2;199;125;209:bd=1;38;2;79;168;216:cd=1;38;2;79;168;216:or=1;38;2;224;96;90"
