# Crimson — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/crimson/theme.toml.
# Sourced from ~/.dots/fish/.config/fish/conf.d/00-rice.fish.

set -gx EZA_CONFIG_DIR ~/.rice/eza

# eza applies LS_COLORS then EZA_COLORS *after* theme.yml, so these reclaim
# the ten classic file-kind codes from whatever LS_COLORS this system
# already exports (dircolors) — matches ~/.rice/eza/theme.yml's filekinds.
set -gx EZA_COLORS "di=1;38;2;168;49;63:ln=3;38;2;79;173;160:ex=1;38;2;217;79;92:pi=38;2;217;149;79:so=38;2;193;79;168:bd=1;38;2;79;143;217:cd=1;38;2;79;143;217:or=1;38;2;255;77;77"
