// Crimson — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/crimson/theme.toml.
// Imported as the "Colors" singleton from ~/.config/quickshell/*.qml via
// `import quickshell` — resolved through QML2_IMPORT_PATH=$HOME/.rice, set
// in ~/.config/environment.d/10-quickshell.conf (quoted-string relative
// imports like `import "../../.rice/quickshell"` don't work here: quickshell
// loads configs into a virtual qs:/ resource tree, so `..` never escapes
// ~/.config/quickshell).
pragma Singleton
import QtQuick

QtObject {
    readonly property color black: "#140808"
    readonly property color surface: "#200d0d"
    readonly property color fg: "#f0e0dd"
    readonly property color white: "#fff5f3"

    readonly property color neon: "#a8313f"
    readonly property color acid: "#d94f5c"
    readonly property color dim: "#4a1f22"
    readonly property color deep: "#331519"
    readonly property color gray: "#6b5452"
    readonly property color gray2: "#8a706d"

    readonly property color red: "#ff4d4d"
    readonly property color amber: "#d9954f"
    readonly property color blue: "#4f8fd9"
    readonly property color magenta: "#c14fa8"
    readonly property color cyan: "#4fada0"
}
