// Toxic — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/toxic.toml.
// Imported as the "Colors" singleton from ~/.config/quickshell/*.qml via
// `import quickshell` — resolved through QML2_IMPORT_PATH=$HOME/.rice, set
// in ~/.config/environment.d/10-quickshell.conf (quoted-string relative
// imports like `import "../../.rice/quickshell"` don't work here: quickshell
// loads configs into a virtual qs:/ resource tree, so `..` never escapes
// ~/.config/quickshell).
pragma Singleton
import QtQuick

QtObject {
    readonly property color black: "#000000"
    readonly property color surface: "#0D1A0D"
    readonly property color fg: "#D9FFD9"
    readonly property color white: "#FFFFFF"

    readonly property color neon: "#39FF14"
    readonly property color acid: "#ADFF2F"
    readonly property color dim: "#1F4D0F"
    readonly property color deep: "#143D0A"
    readonly property color gray: "#4D4D4D"
    readonly property color gray2: "#6C6C6C"

    readonly property color red: "#FF3B30"
    readonly property color amber: "#CCFF00"
    readonly property color blue: "#00BFFF"
    readonly property color magenta: "#FF3FD0"
    readonly property color cyan: "#00E6B8"
}
