// Forest Night — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/forest-night/theme.toml.
// Imported as the "Colors" singleton from ~/.config/quickshell/*.qml via
// `import quickshell` — resolved through QML2_IMPORT_PATH=$HOME/.rice, set
// in ~/.config/environment.d/10-quickshell.conf (quoted-string relative
// imports like `import "../../.rice/quickshell"` don't work here: quickshell
// loads configs into a virtual qs:/ resource tree, so `..` never escapes
// ~/.config/quickshell).
pragma Singleton
import QtQuick

QtObject {
    readonly property color black: "#060b07"
    readonly property color surface: "#132016"
    readonly property color fg: "#d6f2dc"
    readonly property color white: "#fdfefd"

    readonly property color neon: "#2f6b44"
    readonly property color acid: "#4bab6d"
    readonly property color dim: "#1f3725"
    readonly property color deep: "#18291c"
    readonly property color gray: "#4b584e"
    readonly property color gray2: "#6a7c6e"

    readonly property color red: "#e0605a"
    readonly property color amber: "#e0b84f"
    readonly property color blue: "#4fa8d8"
    readonly property color magenta: "#c77dd1"
    readonly property color cyan: "#4fd8b0"
}
