# Crimson — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/crimson/theme.toml.
# Sourced from ~/.dots/fish/.config/fish/conf.d/00-rice.fish, *before*
# fzf.fish's _fzf_wrapper.fish sets its own defaults (it only does that when
# FZF_DEFAULT_OPTS is completely unset) — so this repeats fzf.fish's base
# options and adds --color on top, rather than just appending a color string.

set -gx FZF_DEFAULT_OPTS '--cycle --layout=reverse --border --height=90% --preview-window=wrap --marker="*" --color=fg:#f0e0dd,bg:#140808,hl:#a8313f,fg+:#140808,bg+:#4a1f22,hl+:#d94f5c,info:#d94f5c,border:#4a1f22,prompt:#a8313f,pointer:#a8313f,marker:#d94f5c,spinner:#a8313f,header:#6b5452,gutter:#140808'
