# Forest Night — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/forest-night/theme.toml.
# Sourced from ~/.dots/fish/.config/fish/conf.d/00-rice.fish, *before*
# fzf.fish's _fzf_wrapper.fish sets its own defaults (it only does that when
# FZF_DEFAULT_OPTS is completely unset) — so this repeats fzf.fish's base
# options and adds --color on top, rather than just appending a color string.

set -gx FZF_DEFAULT_OPTS '--cycle --layout=reverse --border --height=90% --preview-window=wrap --marker="*" --color=fg:#d6f2dc,bg:#060b07,hl:#2f6b44,fg+:#060b07,bg+:#1f3725,hl+:#4bab6d,info:#4bab6d,border:#1f3725,prompt:#2f6b44,pointer:#2f6b44,marker:#4bab6d,spinner:#2f6b44,header:#4b584e,gutter:#060b07'
