# laptop — undocked: laptop panel only, externals disabled
# requires: eDP-1
output eDP-1 resolution 1920x1080 position 0,0 transform normal
output "ASUSTek COMPUTER INC ASUS XG49V 0x0002C82E" disable
output "Dell Inc. DELL S2721HS 3953P83" disable
