# Crimson — generated by ~/.rice/bin/apply-theme from ~/.rice/themes/crimson/theme.toml.
# Sourced from ~/.dots/fish/.config/fish/conf.d/00-rice.fish.
#
# Universal (-U), not -g: fish broadcasts universal-variable changes to
# every running fish session immediately, so apply-theme can push a live
# update by sourcing this file once (see reload_fish() in apply-theme)
# instead of every open shell needing to be restarted.

set -U rice_color_dir a8313f
